# Generated by Django 4.2.4 on 2023-09-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_filesadmin_alter_project_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FilesAdmin",
        ),
        migrations.AddField(
            model_name="project",
            name="adminupload",
            field=models.FileField(default="media", upload_to="media"),
        ),
    ]
